CREATE DATABASE restaurant

/* Table to maintain restaurant schedule */
CREATE TABLE SCHEDULE (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
	NAME VARCHAR(15) NOT NULL UNIQUE, 
	FROM_TIME TIME NOT NULL,
	TO_TIME TIME NOT NULL
	)
INSERT INTO SCHEDULE (NAME, FROM_TIME, TO_TIME) VALUES 
	('Breakfast', '08:00:00', '11:00:00'), ('Lunch', '11:15:00', '15:00:00'), 
	('Refreshment', '15:15:00', '23:00:00'), ('Dinner', '19:00:00', '23:00:00')
SELECT * FROM SCHEDULE

/* Table to maintain the list of items available in the restaurant */
CREATE TABLE ITEM (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(20) NOT NULL UNIQUE)
INSERT INTO ITEM (NAME) VALUES ('Idly'), ('Vada'), ('Dosa'), ('Poori'), ('Pongal'), ('Coffee'), ('Tea')
INSERT INTO ITEM (NAME) VALUES ('South Indian Meals'), ('North Indian Thali'), ('Variety Rice')
INSERT INTO ITEM (NAME) VALUES ('Snacks')
INSERT INTO ITEM (NAME) VALUES ('Fried Rice'), ('Chapatti'), ('Chat Items')
SELECT * FROM ITEM

/* Table to maintain the list of items available at a particular time */
CREATE TABLE ITEMS_AVAILABLE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	SCHEDULE_ID INT NOT NULL,
	ITEM_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	CONSTRAINT FK_SCHEDULE_ID FOREIGN KEY(SCHEDULE_ID) REFERENCES SCHEDULE(ID),
	CONSTRAINT FK_ITEM_ID FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ID))
INSERT INTO ITEMS_AVAILABLE (SCHEDULE_ID, ITEM_ID, QUANTITY) VALUES (1,1,100), (1,2,100), (1,3,100), (1,4,100), (1,5,100), (1,6,100), (1,7,100)
INSERT INTO ITEMS_AVAILABLE (SCHEDULE_ID, ITEM_ID, QUANTITY) VALUES (2,8,75), (2,9,75), (2,10,75)
INSERT INTO ITEMS_AVAILABLE (SCHEDULE_ID, ITEM_ID, QUANTITY) VALUES (3,6,200), (3,7,200), (3,11,200)
INSERT INTO ITEMS_AVAILABLE (SCHEDULE_ID, ITEM_ID, QUANTITY) VALUES (4,12,100), (4,13,100), (4,14,100)
SELECT * FROM ITEMS_AVAILABLE

/* Table to maintain the status of the seats available */
CREATE TABLE SEAT (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(10) NOT NULL, STATUS BOOLEAN DEFAULT TRUE NOT NULL)
INSERT INTO SEAT (NAME) VALUES ('A'),('B'),('C'),('D'),('E'),('F'),('G'),('H'),('I'),('J')
SELECT * FROM SEAT

/* Table to maintain transaction details */
CREATE TABLE ORDERS_TRANSACTION (
	ID INT(11) PRIMARY KEY AUTO_INCREMENT, 
	ORDER_ID INT(11) NOT NULL, 
	ITEM_ID INT(11) NOT NULL, 
	QUANTITY INT(11) NOT NULL, 
	TIME_STAMP DATETIME NOT NULL, 
	STATUS VARCHAR(20),
	CONSTRAINT FK_ORDERS_ITEM_ID FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ID))

/* Table to maintain the order and seat details */
CREATE TABLE ORDER_INFO (
	ID INT(11) PRIMARY KEY AUTO_INCREMENT, SEAT_ID INT(11) NOT NULL, STATUS VARCHAR(20) NOT NULL DEFAULT 'Requested', 
	CONSTRAINT FK_SEAT_ID FOREIGN KEY(SEAT_ID) REFERENCES SEAT(ID))