/* To provide the view of available menu items in particular time */
CREATE VIEW VW_MEAL_MENU AS
	SELECT ITEMS_AVAILABLE.`ITEM_ID`, ITEM.`NAME`, SCHEDULE.`ID` AS SCHEDULE_ID 
	FROM ITEM, ITEMS_AVAILABLE 
	JOIN SCHEDULE 
	ON ITEMS_AVAILABLE.`SCHEDULE_ID`=SCHEDULE.`ID` 
	WHERE NOW() BETWEEN FROM_TIME AND TO_TIME
	AND ITEMS_AVAILABLE.`ITEM_ID`=ITEM.`ID`
SELECT * FROM VW_MEAL_MENU

/*  To view the stock details */
CREATE VIEW VW_STOCK AS
	SELECT IA.`ITEM_ID`, ITEM.`NAME` AS ITEM_NAME, S.`NAME` AS SCHEDULE_NAME, IA.`QUANTITY` AS TOTAL, 
		IFNULL(SUM(O.`QUANTITY`),0) AS CONSUMED, 
		IFNULL(IA.`QUANTITY`-SUM(O.`QUANTITY`),IA.`QUANTITY`) AS REMAINING 
	FROM ITEMS_AVAILABLE IA
	LEFT JOIN ITEM 
	ON ITEM.`ID`=IA.`ITEM_ID`
	LEFT JOIN SCHEDULE S
	ON S.`ID`=IA.`SCHEDULE_ID`
	LEFT JOIN ORDERS_TRANSACTION O
	ON O.ITEM_ID = ITEM.`ID` 
	AND EXISTS 
		( SELECT 1 FROM SCHEDULE WHERE ID = S.ID AND TIME(O.`TIME_STAMP`) BETWEEN FROM_TIME AND TO_TIME )
	AND DATE(O.`TIME_STAMP`)=CURDATE()
	AND O.`STATUS`='Ordered'
	GROUP BY IA.`ID`
SELECT * FROM VW_STOCK